export enum BookingStatus {
	PENDING = 'PENDING',
	PAID = 'PAID',
	APPROVED = 'APPROVED',
	REJECTED = 'REJECTED',
	ACTIVE = 'ACTIVE',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
	DELETED = 'DELETED',
}

export enum PaymentStatus {
	UNPAID = 'UNPAID',
	PAID = 'PAID',
	REFUNDED = 'REFUNDED',
}
