export enum BrandType {
	BMW = 'BMW',
	MERCEDES = 'MERCEDES',
	VOLKSWAGEN = 'VOLKSWAGEN',
	JAGUAR = 'JAGUAR',
	LEXUS = 'LEXUS',
	AUDI = 'AUDI',
	HONDA = 'HONDA',
	KIA = 'KIA',
	HYUNDAI = 'HYUNDAI',
	TESLA = 'TESLA',
	CHEVROLET = 'CHEVROLET',
	GENESIS = 'GENESIS',
}

export enum FuelType {
	GASOLINE = 'GASOLINE',
	LPG = 'LPG',
	DIESEL = 'DIESEL',
	HYBRID = 'HYBRID',
	ELECTRIC = 'ELECTRIC',
}

export enum Transmission {
	AUTOMATIC = 'AUTOMATIC',
	MANUAL = 'MANUAL',
}

export enum CarType {
	SPORT = 'SPORT',
	HATCHBACK = 'HATCHBACK',
	SEDAN = 'SEDAN',
	SUV = 'SUV',
	CROSSOVER = 'CROSSOVER',
	COUPE = 'COUPE',
	MINIVAN = 'MINIVAN',
	CONVERTIBLE = 'CONVERTIBLE',
	PICKUP = 'PICKUP',
	OTHER = 'OTHER',
}

export enum CarStatus {
	ACTIVE = 'ACTIVE',
	BLOCKED = 'BLOCKED',
	DELETED = 'DELETED',
}

export enum CarLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	DAEGU = 'DAEGU',
	INCHEON = 'INCHEON',
	GWANGJU = 'GWANGJU',
	DAEJEON = 'DAEJEON',
	ULSAN = 'ULSAN',
	SEJONG = 'SEJONG',
	OTHER = 'OTHER',
}
