services:
  nestar-next:
    container_name: carento-front
    restart: always
    image: node:20.10.0
    ports:
      - 4021:4020
    environment:
      - PORT=4020
    volumes:
      - ./:/usr/src/carento-front
    working_dir: /usr/src/carento-front

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn build && yarn start"

networks:
  client-network:
    driver: bridge
# nestar-next:  localhost:4000 <=> container:3000
# nestar-api:   localhost:4001 <=> container:3007
# nestar-batch: localhost:4002 <=> container:3008
